"""Shared instrumentation contracts used by strategy families and OMS code."""
from .event_contract import (
    COMMON_LINEAGE_FIELDS,
    enrich_envelope,
    event_schema_version,
    event_scope,
    merge_lineage,
    write_decision_event,
    write_error_event,
    write_risk_halt_event,
    write_strategy_decision_event,
)
from .deployment_metadata import build_deployment_metadata, write_deployment_metadata
from .lineage import (
    LineageContext,
    canonical_json,
    compute_allocation_version,
    compute_code_sha,
    compute_portfolio_config_version,
    compute_risk_config_version,
    compute_strategy_config_version,
    compute_strategy_registry_version,
    lineage_from_config,
    lineage_from_runtime,
    lineage_to_payload,
    redact_config,
    resolve_deployment_id,
    stable_hash,
)

__all__ = [
    "COMMON_LINEAGE_FIELDS",
    "LineageContext",
    "build_deployment_metadata",
    "canonical_json",
    "compute_allocation_version",
    "compute_code_sha",
    "compute_portfolio_config_version",
    "compute_risk_config_version",
    "compute_strategy_config_version",
    "compute_strategy_registry_version",
    "enrich_envelope",
    "event_schema_version",
    "event_scope",
    "lineage_from_runtime",
    "lineage_from_config",
    "lineage_to_payload",
    "merge_lineage",
    "redact_config",
    "resolve_deployment_id",
    "stable_hash",
    "write_decision_event",
    "write_deployment_metadata",
    "write_error_event",
    "write_risk_halt_event",
    "write_strategy_decision_event",
]
