"""Shared contract surface for the trading workspace."""

from trading_contracts.models import (
    BacktestArtifactIndex,
    ConfirmatoryRerank,
    DataBundleManifest,
    DecisionParityCheck,
    DecisionParityReport,
    DecisionParityStatus,
    MonthlyRunManifest,
    RoundManifestRecord,
    RoundsManifest,
    StrategyPluginContract,
    StrategyPluginMaturity,
)

from trading_contracts.canonical import canonical_json_sha256, canonical_json_text, file_sha256
from trading_contracts.legacy import (
    CryptoDeploymentManifestV1,
    CryptoOptimizerContractV1,
    KStockOlrKalcbStrategyPluginContractV1,
    LegacyRoundsManifest,
    StrategyPromotionManifest,
    load_rounds_manifest,
    validate_deployment_manifest,
    validate_plugin_contract,
    validate_promotion_manifest,
    validate_rounds_manifest,
)
from trading_contracts.relay_acceptance import (
    RelayProbeResult,
    canonical_relay_body,
    contains_placeholder,
    deployment_heartbeat_envelope,
    deployment_heartbeat_event,
    probe_relay_acceptance,
    relay_signature,
    secret_fingerprint,
    validate_hmac_secret,
    validate_identifier_field,
    validate_relay_config,
    validate_relay_url,
)
from trading_contracts.relay_evidence import (
    RELAY_EVIDENCE_MAX_AGE_SECONDS,
    relay_freshness_errors,
    relay_metadata_hashes,
    relay_secret_fingerprint,
    validate_relay_ingest_evidence,
)
from trading_contracts.runtime import (
    DeploymentMetadata,
    ReadinessCheck,
    RuntimeReadinessReport,
    TelemetryEventEnvelope,
)

__all__ = [
    "BacktestArtifactIndex",
    "ConfirmatoryRerank",
    "CryptoDeploymentManifestV1",
    "CryptoOptimizerContractV1",
    "DataBundleManifest",
    "DecisionParityCheck",
    "DecisionParityReport",
    "DecisionParityStatus",
    "DeploymentMetadata",
    "KStockOlrKalcbStrategyPluginContractV1",
    "LegacyRoundsManifest",
    "MonthlyRunManifest",
    "ReadinessCheck",
    "RelayProbeResult",
    "RELAY_EVIDENCE_MAX_AGE_SECONDS",
    "RoundManifestRecord",
    "RoundsManifest",
    "RuntimeReadinessReport",
    "StrategyPluginContract",
    "StrategyPluginMaturity",
    "StrategyPromotionManifest",
    "TelemetryEventEnvelope",
    "canonical_json_sha256",
    "canonical_json_text",
    "canonical_relay_body",
    "contains_placeholder",
    "deployment_heartbeat_envelope",
    "deployment_heartbeat_event",
    "file_sha256",
    "load_rounds_manifest",
    "probe_relay_acceptance",
    "relay_signature",
    "secret_fingerprint",
    "relay_freshness_errors",
    "relay_metadata_hashes",
    "relay_secret_fingerprint",
    "validate_hmac_secret",
    "validate_identifier_field",
    "validate_deployment_manifest",
    "validate_plugin_contract",
    "validate_promotion_manifest",
    "validate_relay_config",
    "validate_relay_ingest_evidence",
    "validate_relay_url",
    "validate_rounds_manifest",
]
