"""Compatibility aliases for canonical contract models.

The canonical implementations live in :mod:`trading_contracts.models`.
"""

from __future__ import annotations

from trading_contracts.models import (
    DECISION_PARITY_DIMENSIONS,
    JSONL_ARTIFACTS,
    JSON_ARTIFACTS,
    MONTHLY_OPTIMIZER_WORKFLOW_CONTRACT_VERSION,
    OBJECTIVE_WEIGHTS_VERSION,
    OPTIONAL_BACKTEST_ARTIFACTS,
    PHASE4_OOS_REPAIR_ARTIFACTS,
    PHASE4_OPTIMIZER_ARTIFACTS,
    PHASE4_STRUCTURAL_CANDIDATE_ARTIFACTS,
    PHASED_AUTO_RUNNER_CONTRACT_VERSION,
    REQUIRED_BACKTEST_ARTIFACTS,
    SMOKE_REPAIR_RUNNER_CONTRACT_VERSION,
    TWO_FOLD_PURGED_MANIFEST_VERSION,
    BacktestArtifactIndex,
    BacktestExitStatus,
    CandidateAttemptRecord,
    CandidateAttemptState,
    CandidateWorkspaceManifest,
    ConfirmatoryRerank,
    ConfirmatoryVariant,
    DataBundleManifest,
    DataBundleSlice,
    DataBundleStatus,
    DecisionParityCheck,
    DecisionParityReport,
    DecisionParityStatus,
    FoldManifest,
    FoldSpec,
    MonthlyApprovalMode,
    MonthlyCandidateSource,
    MonthlyRunManifest,
    MonthlyRunMode,
    OptimizerExperimentPlan,
    OptimizerStage,
    RoundManifestRecord,
    RoundsManifest,
    StrategyPluginContract,
    StrategyPluginMaturity,
    build_two_fold_manifest,
    sanitize_workspace_key,
)

__all__ = [
    "DECISION_PARITY_DIMENSIONS",
    "JSONL_ARTIFACTS",
    "JSON_ARTIFACTS",
    "MONTHLY_OPTIMIZER_WORKFLOW_CONTRACT_VERSION",
    "OBJECTIVE_WEIGHTS_VERSION",
    "OPTIONAL_BACKTEST_ARTIFACTS",
    "PHASE4_OOS_REPAIR_ARTIFACTS",
    "PHASE4_OPTIMIZER_ARTIFACTS",
    "PHASE4_STRUCTURAL_CANDIDATE_ARTIFACTS",
    "PHASED_AUTO_RUNNER_CONTRACT_VERSION",
    "REQUIRED_BACKTEST_ARTIFACTS",
    "SMOKE_REPAIR_RUNNER_CONTRACT_VERSION",
    "TWO_FOLD_PURGED_MANIFEST_VERSION",
    "BacktestArtifactIndex",
    "BacktestExitStatus",
    "CandidateAttemptRecord",
    "CandidateAttemptState",
    "CandidateWorkspaceManifest",
    "ConfirmatoryRerank",
    "ConfirmatoryVariant",
    "DataBundleManifest",
    "DataBundleSlice",
    "DataBundleStatus",
    "DecisionParityCheck",
    "DecisionParityReport",
    "DecisionParityStatus",
    "FoldManifest",
    "FoldSpec",
    "MonthlyApprovalMode",
    "MonthlyCandidateSource",
    "MonthlyRunManifest",
    "MonthlyRunMode",
    "OptimizerExperimentPlan",
    "OptimizerStage",
    "RoundManifestRecord",
    "RoundsManifest",
    "StrategyPluginContract",
    "StrategyPluginMaturity",
    "build_two_fold_manifest",
    "sanitize_workspace_key",
]
