"""Run the latest controlled-aggressive swing portfolio-synergy phase auto round.

The round starts from the latest individual swing artifacts (ATRSS round 3,
AKC Helix round 5, TPC round 8) unless an explicit base config is supplied.
It borrows the momentum portfolio optimizer's structure: expected return and
trade frequency lead the score, but dynamic risk tiers, contribution balance,
and hard drawdown gates prevent the portfolio from simply buying more heat.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT))

from backtests.shared.auto.cache_keys import build_cache_key, fingerprint_paths, fingerprint_tree, stable_signature
from backtests.shared.auto.phase_runner import PhaseRunner
from backtests.shared.auto.plugin import PhaseAnalysisPolicy, PhaseSpec
from backtests.shared.auto.provenance import AutoRunProvenance, build_phase_auto_provenance
from backtests.shared.auto.plugin_utils import (
    CachedBatchEvaluator,
    ResilientBatchEvaluator,
    SharedPoolBatchEvaluator,
    create_process_pool,
    mutation_signature,
    resolve_worker_processes,
    shutdown_process_pool,
)
from backtests.shared.auto.replay_bundle import ReplayBundle
from backtests.shared.auto.round_manager import RoundManager
from backtests.shared.auto.types import EndOfRoundArtifacts, Experiment, GateCriterion, GreedyResult, ScoredCandidate
from backtests.swing.analysis.metrics import PerformanceMetrics
from backtests.swing.auto.greedy_optimize import (
    _init_worker,
    _score_config,
    _worker_score,
)
from backtests.swing.config_unified import UnifiedBacktestConfig
from backtests.swing.engine.unified_portfolio_engine import UnifiedPortfolioData, load_unified_data

from backtests.swing.auto.portfolio_synergy.run_latest_two_rounds import (
    LATEST_CONFIGS,
    LIVE_SEED_MUTATIONS,
    OPTIMIZATION_RETURN_BASIS,
    _evaluate,
    _json_default,
)


SCORE_PROFILE = "portfolio_synergy_alpha_frequency"
STARTING_EQUITY = 50_000.0
RISK_STANCE = "controlled_aggressive"
ROUND_NAME = "round_1_phase_auto"
REPLAY_ARCHITECTURE = "unified_bar_replay_shared_swing_live_risk_adapters"
LIVE_SWING_RISK_ADAPTER = "libs.oms.risk.swing_portfolio_adapter.evaluate_swing_entry"
LIVE_PORTFOLIO_RULE_CHECKER = "libs.oms.risk.portfolio_rules.PortfolioRuleChecker"
LIVE_STRATEGY_COORDINATOR = "libs.oms.coordination.coordinator.StrategyCoordinator"
PORTFOLIO_REPLAY_SCOPE = (
    "ATRSS and AKC Helix use their source backtest engines, which mirror live "
    "state and replay core events but still contain engine-side strategy decisions; "
    "TPC is generated by the shared ETF core replay and contributes source-engine "
    "completed trades that are re-admitted through the shared swing portfolio "
    "layer as portfolio sizing/admission evidence."
)
THIN_LAYER_ASSESSMENT = {
    "portfolio_risk_layer": {
        "status": "thin_over_live_risk_and_coordination",
        "evidence": (
            "Portfolio entry admission, heat/rule checks, and cross-strategy "
            "coordination reuse SwingPortfolioHeatAdapter, PortfolioRuleChecker, "
            "and StrategyCoordinator from live OMS services."
        ),
        "remaining_gap": (
            "The portfolio replay still normalises source-engine fills into a "
            "shared equity ledger, but the policy decisions are delegated to live "
            "risk and coordination services."
        ),
    },
    "ATRSS": {
        "status": "mixed_not_optimal_thin_layer",
        "evidence": (
            "The source backtest and live engine both route state through the ATRSS "
            "core for selected events, but candidate generation, order submission, "
            "position management, reversals, and exits still live in engine code."
        ),
        "migration_needed": (
            "Move candidate/order/exit transitions into the ATRSS shared core and "
            "make live/backtest wrappers translate neutral actions only."
        ),
    },
    "AKC_HELIX": {
        "status": "mixed_not_optimal_thin_layer",
        "evidence": (
            "The Helix engines hydrate/replay core state, but setup detection, "
            "queueing, arming, pending management, and exit paths remain engine-owned."
        ),
        "migration_needed": (
            "Move setup lifecycle and exit decisions into the Helix shared core and "
            "leave OMS/SimBroker translation in the adapters."
        ),
    },
    "TPC": {
        "status": "thin_source_replay",
        "evidence": (
            "TPC live and backtest both use the ETF shared core path; the backtest "
            "drives core on_bar/on_fill/on_order_update and translates neutral "
            "actions into SimBroker orders."
        ),
        "remaining_gap": (
            "In the portfolio engine, completed source trades are replayed for "
            "admission/sizing evidence rather than stepping the TPC core inside the "
            "family timeline."
        ),
    },
}
PHASE_SOURCE_CONFIGS = {
    **LATEST_CONFIGS,
    "ATRSS": ROOT / "backtests" / "output" / "swing" / "atrss" / "round_3" / "optimized_config.json",
}
PHASE_SOURCE_DIAGNOSTICS = {
    "ATRSS": ROOT / "backtests" / "output" / "swing" / "atrss" / "round_3" / "full_diagnostics_summary.json",
    "AKC_HELIX": ROOT / "backtests" / "output" / "swing" / "helix" / "round_5" / "diagnostics_summary.json",
    "TPC": ROOT / "backtests" / "output" / "swing" / "tpc" / "round_8" / "run_summary.json",
}
PHASE_SOURCE_SCOPES = {
    "ATRSS": "current-code synchronized round_3 full diagnostics",
    "AKC_HELIX": "current-code synchronized round_5 final diagnostics",
    "TPC": "round_8 train-only source diagnostics; portfolio replay applies the optimized config to its configured replay window",
}

DIAGNOSTIC_ASSESSMENTS: list[dict[str, Any]] = [
    {
        "strategy_id": "ATRSS",
        "latest_round": "round_3",
        "assessment": (
            "High-PF/high-expectancy engine from the regenerated round 3 artifact: "
            "264 trades, 234.8R, PF 6.58, 7.82% DD, and seven-component score 0.7128. "
            "Strict OOS has only 2 trades after the structural repair, so this round "
            "treats ATRSS as a strong alpha sleeve but avoids new ATRSS micro-filter overfitting."
        ),
        "portfolio_implication": "Overweight carefully; unlock blocked entries through smaller unit risk plus more sleeve heat, not extra signal filters.",
    },
    {
        "strategy_id": "AKC_HELIX",
        "latest_round": "round_5",
        "assessment": (
            "Current round 5 artifact is the synchronized Helix sleeve after the OOS repair "
            "and trail-fade penalty pass: 325 diagnostic trades, 158.8R, PF 2.17, "
            "182.9% net return on $25k, and 5.96% DD. The OOS sample remains small, "
            "so this round should lean on portfolio-level risk allocation and broad gates "
            "rather than adding narrow Helix-only filters."
        ),
        "portfolio_implication": "Keep as a primary return sleeve; size it dynamically with heat and DD tiers while avoiding fresh micro-filter overfit.",
    },
    {
        "strategy_id": "TPC",
        "latest_round": "round_8",
        "assessment": (
            "Valid but lower-capacity complement: 127 train-only source trades, "
            "86.5R, $PF 2.08, 13.7% DD, and a small 6-trade additive lane. "
            "Round 8 correctly removed the unsupported T2 extension after holdout checks."
        ),
        "portfolio_implication": "Use TPC for frequency and diversification, but require minimum direct participation and prefer lower source risk when giving it more heat.",
    },
]

PHASE_SCORING_KWARGS = {
    "max_drawdown_hard_pct": 0.16,
    "drawdown_comfort_pct": 0.115,
    "alpha_return_target_pct": 520.0,
    "trade_count_target": 620,
    "trades_per_month_target": 10.5,
    "total_r_per_month_target": 6.5,
    "accept_rate_target": 0.70,
    "min_profit_factor": 2.40,
    "pf_quality_floor": 2.20,
    "pf_quality_target": 3.80,
    "sharpe_quality_target": 3.20,
    "min_trades": 520,
    "required_strategies": ("ATRSS", "AKC_HELIX", "TPC"),
    "min_required_strategy_trades": 25,
    "strategy_active_trade_floor": 25.0,
    "strategy_min_trade_target": 120.0,
    "max_single_strategy_static_pnl_share": 0.80,
    "score_weights": {
        "alpha_quality": 0.30,
        "frequency_quality": 0.24,
        "drawdown_quality": 0.16,
        "pf_quality": 0.09,
        "balance_quality": 0.10,
        "capture_quality": 0.07,
        "robustness_quality": 0.04,
    },
}


PHASES: list[tuple[str, list[tuple[str, dict[str, Any]]]]] = [
    (
        "phase_1_controlled_aggressive_seed",
        [
            (
                "controlled_aggressive_core",
                {
                    "heat_cap_R": 4.25,
                    "portfolio_daily_stop_R": 3.25,
                    "dynamic_risk_enabled": True,
                    "drawdown_risk_tiers": (
                        (0.05, 1.00),
                        (0.08, 0.80),
                        (0.12, 0.55),
                        (0.16, 0.25),
                        (0.18, 0.00),
                    ),
                    "overlay_max_pct": 0.55,
                    "atrss.unit_risk_pct": 0.014,
                    "atrss.max_heat_R": 2.10,
                    "helix.unit_risk_pct": 0.0085,
                    "helix.max_heat_R": 1.60,
                    "tpc.unit_risk_pct": 0.004,
                    "tpc.max_heat_R": 1.75,
                    "symbol_risk_multipliers": {"ATRSS:QQQ": 0.85, "ATRSS:GLD": 0.85},
                },
            ),
            (
                "balanced_50k_risk_units",
                {
                    "heat_cap_R": 4.50,
                    "portfolio_daily_stop_R": 3.50,
                    "dynamic_risk_enabled": True,
                    "drawdown_risk_tiers": (
                        (0.06, 1.00),
                        (0.10, 0.75),
                        (0.14, 0.45),
                        (0.18, 0.00),
                    ),
                    "atrss.unit_risk_pct": 0.0125,
                    "atrss.max_heat_R": 2.35,
                    "helix.unit_risk_pct": 0.0075,
                    "helix.max_heat_R": 1.80,
                    "tpc.unit_risk_pct": 0.0035,
                    "tpc.max_heat_R": 2.25,
                },
            ),
            (
                "strict_dd_recovery_throttle",
                {
                    "dynamic_risk_enabled": True,
                    "drawdown_risk_tiers": (
                        (0.04, 0.90),
                        (0.07, 0.70),
                        (0.10, 0.50),
                        (0.14, 0.25),
                        (0.18, 0.00),
                    ),
                    "portfolio_daily_stop_R": 3.00,
                },
            ),
            ("overlay_55_multi", {"overlay_max_pct": 0.55, "overlay_mode": "multi"}),
            ("overlay_45_multi", {"overlay_max_pct": 0.45, "overlay_mode": "multi"}),
            ("overlay_off_dd_probe", {"overlay_enabled": False}),
        ],
    ),
    (
        "phase_2_dynamic_sleeve_allocation",
        [
            (
                "atrss_smaller_unit_more_heat",
                {
                    "atrss.unit_risk_pct": 0.012,
                    "atrss.max_heat_R": 2.55,
                    "symbol_risk_multipliers": {"ATRSS:QQQ": 0.80, "ATRSS:GLD": 0.90},
                },
            ),
            (
                "helix_smaller_unit_more_heat",
                {
                    "helix.unit_risk_pct": 0.0075,
                    "helix.max_heat_R": 2.00,
                    "helix_param.ADD_RISK_FRAC": 1.20,
                },
            ),
            (
                "tpc_lower_unit_more_heat",
                {
                    "tpc.unit_risk_pct": 0.003,
                    "tpc.max_heat_R": 3.00,
                    "tpc_param.all.max_risk_pct": 0.012,
                    "tpc_param.all.risk_a_plus_pct": 0.012,
                    "tpc_param.all.risk_a_pct": 0.008,
                    "tpc_param.all.risk_b_pct": 0.005,
                    "tpc_param.all.max_position_notional_pct": 6.0,
                },
            ),
            (
                "helix_atrss_barbell",
                {
                    "atrss.unit_risk_pct": 0.013,
                    "atrss.max_heat_R": 2.25,
                    "helix.unit_risk_pct": 0.008,
                    "helix.max_heat_R": 1.90,
                    "tpc.unit_risk_pct": 0.0035,
                    "tpc.max_heat_R": 2.25,
                },
            ),
        ],
    ),
    (
        "phase_3_blocked_alpha_routing",
        [
            ("no_idle_priority_reservation", {"reserve_idle_higher_priority": False}),
            (
                "tpc_middle_priority_lowrisk",
                {
                    "atrss.priority": 0,
                    "tpc.priority": 1,
                    "helix.priority": 2,
                    "tpc.unit_risk_pct": 0.003,
                    "tpc.max_heat_R": 2.75,
                },
            ),
            (
                "tpc_first_micro_size",
                {
                    "tpc.priority": 0,
                    "atrss.priority": 1,
                    "helix.priority": 2,
                    "tpc.unit_risk_pct": 0.0025,
                    "tpc.max_heat_R": 3.50,
                    "tpc_param.all.max_risk_pct": 0.010,
                    "tpc_param.all.risk_a_plus_pct": 0.010,
                    "tpc_param.all.risk_a_pct": 0.006,
                    "tpc_param.all.risk_b_pct": 0.004,
                },
            ),
            ("disable_atrss_helix_size_boost", {"enable_atrss_helix_size_boost": False}),
            ("disable_atrss_helix_tighten", {"enable_atrss_helix_tighten": False}),
            (
                "disable_cross_boost_and_tighten",
                {
                    "enable_atrss_helix_size_boost": False,
                    "enable_atrss_helix_tighten": False,
                },
            ),
        ],
    ),
    (
        "phase_4_winner_loser_discrimination",
        [
            ("helix_add_risk_1_10", {"helix_param.ADD_RISK_FRAC": 1.10}),
            ("helix_add_risk_0_95", {"helix_param.ADD_RISK_FRAC": 0.95}),
            ("helix_staler_exit_20", {"helix_param.EARLY_STALE_BARS": 20}),
            ("helix_trail_stall_3", {"helix_param.TRAIL_STALL_ONSET": 3}),
            ("tpc_quality_threshold_plus1", {"tpc_param.all.score_a_min": 11, "tpc_param.all.score_b_min": 10}),
            (
                "tpc_low_mfe_guard",
                {
                    "tpc_param.all.confirmation_required": 2,
                    "tpc_param.all.score_a_plus_min": 14,
                    "tpc_param.all.second_entry_score_min": 16,
                },
            ),
            ("atrss_source_risk_1_8", {"atrss_param.base_risk_pct": 0.018}),
            ("atrss_source_risk_2_0", {"atrss_param.base_risk_pct": 0.020}),
        ],
    ),
    (
        "phase_5_final_aggressive_refinement",
        [
            ("portfolio_heat4_75", {"heat_cap_R": 4.75}),
            ("portfolio_heat5_25_probe", {"heat_cap_R": 5.25}),
            ("daily_stop3_75", {"portfolio_daily_stop_R": 3.75}),
            (
                "balanced_heat5_lower_units",
                {
                    "heat_cap_R": 5.00,
                    "atrss.unit_risk_pct": 0.012,
                    "atrss.max_heat_R": 2.50,
                    "helix.unit_risk_pct": 0.0075,
                    "helix.max_heat_R": 1.90,
                    "tpc.unit_risk_pct": 0.003,
                    "tpc.max_heat_R": 3.00,
                },
            ),
            (
                "tpc_heat3_lower_source_final",
                {
                    "tpc.unit_risk_pct": 0.003,
                    "tpc.max_heat_R": 3.00,
                    "tpc_param.all.max_risk_pct": 0.010,
                    "tpc_param.all.risk_a_plus_pct": 0.010,
                    "tpc_param.all.risk_a_pct": 0.006,
                    "tpc_param.all.risk_b_pct": 0.004,
                },
            ),
        ],
    ),
]


def _score_phase_candidate_worker(task: tuple[str, dict[str, Any]]) -> ScoredCandidate:
    name, mutations = task
    score_value, rejected, reason = _worker_score(mutations)
    return ScoredCandidate(
        name=name,
        score=0.0 if rejected else float(score_value),
        rejected=bool(rejected),
        reject_reason=str(reason or ""),
        metrics={},
    )


def _metrics_to_dict(metrics: PerformanceMetrics) -> dict[str, float]:
    return {key: getattr(metrics, key) for key in metrics.__dataclass_fields__}


class PortfolioSynergyPhasePlugin:
    name = "portfolio_synergy"
    num_phases = len(PHASES)

    def __init__(
        self,
        data_dir: Path,
        *,
        initial_equity: float = STARTING_EQUITY,
        max_workers: int | None = 2,
        initial_mutations: dict[str, Any] | None = None,
        base_source: str = "phase_source_configs_atrss_round_3_helix_round_5",
    ) -> None:
        self.data_dir = Path(data_dir)
        self.initial_equity = float(initial_equity)
        self.max_workers = max_workers
        self.initial_mutations = dict(initial_mutations or phase_latest_strategy_mutations())
        self.base_source = base_source
        self.initial_mutations_source = base_source
        self._data = None
        self._cached_bundle: ReplayBundle[UnifiedPortfolioData] | None = None
        self._cache_source_fingerprint = ""
        self._metrics_cache: dict[str, dict[str, Any]] = {}
        self._score_cache: dict[str, ScoredCandidate] = {}
        self._provenance: AutoRunProvenance | None = None

    def build_provenance(self) -> AutoRunProvenance:
        if self._provenance is None:
            source_artifacts = {
                f"{sid}:optimized_config": path
                for sid, path in PHASE_SOURCE_CONFIGS.items()
            }
            source_artifacts.update(
                {
                    f"{sid}:diagnostics": path
                    for sid, path in PHASE_SOURCE_DIAGNOSTICS.items()
                }
            )
            self._provenance = build_phase_auto_provenance(
                self.name,
                repo_root=ROOT,
                code_dirs=(Path(__file__).resolve().parent,),
                code_paths=(
                    Path(__file__).resolve(),
                    ROOT / "backtests/swing/engine/unified_portfolio_engine.py",
                    ROOT / "strategies/swing/overlay/engine.py",
                    ROOT / "libs/oms/risk/portfolio_rules.py",
                    ROOT / "libs/oms/risk/swing_portfolio_adapter.py",
                ),
                data_dir=self.data_dir,
                source_artifacts=source_artifacts,
                selection_context={
                    "initial_equity": self.initial_equity,
                    "base_source": self.base_source,
                    "risk_stance": RISK_STANCE,
                    "score_profile": SCORE_PROFILE,
                    "return_basis": OPTIMIZATION_RETURN_BASIS,
                    "replay_architecture": REPLAY_ARCHITECTURE,
                    "phase_scoring_kwargs": PHASE_SCORING_KWARGS,
                    "phase_count": self.num_phases,
                    "round_baseline_policy": "run_spec.baseline_mutations",
                },
            )
        return self._provenance

    @property
    def ultimate_targets(self) -> dict[str, float]:
        return {
            "net_return_pct": float(PHASE_SCORING_KWARGS["alpha_return_target_pct"]),
            "total_trades": float(PHASE_SCORING_KWARGS.get("trade_count_target", PHASE_SCORING_KWARGS["min_trades"])),
            "profit_factor": float(PHASE_SCORING_KWARGS["min_profit_factor"]),
            "max_drawdown_pct": float(PHASE_SCORING_KWARGS["max_drawdown_hard_pct"]) * 100.0,
            "heat_max_R": 4.75,
        }

    def get_phase_spec(self, phase: int, state) -> PhaseSpec:
        del state
        phase_name, candidate_pairs = PHASES[phase - 1]
        return PhaseSpec(
            focus=phase_name,
            candidates=[Experiment(name=name, mutations=dict(mutations)) for name, mutations in candidate_pairs],
            gate_criteria_fn=self._gate_criteria,
            scoring_weights=dict(PHASE_SCORING_KWARGS["score_weights"]),
            hard_rejects={
                "max_drawdown_hard_pct": PHASE_SCORING_KWARGS["max_drawdown_hard_pct"],
                "min_profit_factor": PHASE_SCORING_KWARGS["min_profit_factor"],
                "min_trades": PHASE_SCORING_KWARGS["min_trades"],
                "min_required_strategy_trades": PHASE_SCORING_KWARGS["min_required_strategy_trades"],
                "max_single_strategy_static_pnl_share": PHASE_SCORING_KWARGS[
                    "max_single_strategy_static_pnl_share"
                ],
            },
            analysis_policy=PhaseAnalysisPolicy(
                focus_metrics=[
                    "net_return_pct",
                    "total_trades",
                    "profit_factor",
                    "max_drawdown_pct",
                    "heat_max_R",
                ],
                min_effective_score_delta_pct=0.005,
                diagnostic_gap_fn=_phase_diagnostic_gaps,
            ),
            max_rounds=12,
            prune_threshold=0.02,
            reject_streak_limit=1,
        )

    def create_evaluate_batch(
        self,
        phase: int,
        cumulative_mutations: dict[str, Any],
        *,
        scoring_weights: dict[str, float] | None = None,
        hard_rejects: dict[str, float] | None = None,
    ):
        del cumulative_mutations
        scoring_kwargs = dict(PHASE_SCORING_KWARGS)
        scoring_kwargs.update(hard_rejects or {})
        if scoring_weights:
            scoring_kwargs["score_weights"] = dict(scoring_weights)
        if len(scoring_kwargs.get("score_weights", {})) > 7:
            raise ValueError("Swing portfolio synergy scoring cannot use more than 7 components.")
        bundle = self._ensure_bundle()
        evaluation_key = build_cache_key(
            "swing.portfolio_synergy.evaluation",
            source_fingerprint=bundle.cache_source_fingerprint,
            extra={
                "phase": phase,
                "score_profile": SCORE_PROFILE,
                "score_components": list(scoring_kwargs.get("score_weights", {}).keys()),
                "scoring_weights": scoring_weights or {},
                "hard_rejects": hard_rejects or {},
                "return_basis": OPTIMIZATION_RETURN_BASIS,
                "initial_equity": self.initial_equity,
                "risk_stance": RISK_STANCE,
                "data_dir": str(self.data_dir.resolve()),
            },
        )

        def _local(candidates: list[Experiment], current_mutations: dict[str, Any]) -> list[ScoredCandidate]:
            results: list[ScoredCandidate] = []
            for candidate in candidates:
                merged = dict(current_mutations)
                merged.update(candidate.mutations)
                score, metrics, score_net_profit = _score_config(
                    self._replay_data(),
                    merged,
                    self.initial_equity,
                    OPTIMIZATION_RETURN_BASIS,
                    scoring_kwargs,
                    SCORE_PROFILE,
                )
                metrics_dict = _metrics_to_dict(metrics)
                metrics_dict["score_net_profit"] = float(score_net_profit)
                results.append(
                    ScoredCandidate(
                        name=candidate.name,
                        score=0.0 if score.rejected else float(score.total),
                        rejected=bool(score.rejected),
                        reject_reason=str(score.reject_reason or ""),
                        metrics=metrics_dict,
                    )
                )
            return results

        local = CachedBatchEvaluator(
            _local,
            cache=self._score_cache,
            metrics_cache=self._metrics_cache,
            signature_prefix=f"{self.name}:local:{evaluation_key}",
        )
        if resolve_worker_processes(self.max_workers) <= 1:
            return local

        def _build_args(candidates: list[Experiment], current_mutations: dict[str, Any]):
            args: list[tuple[str, dict[str, Any]]] = []
            for candidate in candidates:
                merged = dict(current_mutations)
                merged.update(candidate.mutations)
                args.append((candidate.name, merged))
            return args

        def _parallel_factory():
            pool = create_process_pool(
                self.max_workers,
                initializer=_init_worker,
                initargs=(
                    str(self.data_dir),
                    self.initial_equity,
                    OPTIMIZATION_RETURN_BASIS,
                    scoring_kwargs,
                    SCORE_PROFILE,
                ),
                logger=logging.getLogger(__name__),
                description="portfolio synergy phase auto",
            )
            return SharedPoolBatchEvaluator(
                pool,
                worker_fn=_score_phase_candidate_worker,
                build_args=_build_args,
                on_terminate=lambda: shutdown_process_pool(pool, force=True),
                on_close=lambda: shutdown_process_pool(pool, force=False),
                description="portfolio synergy candidate batch",
                logger=logging.getLogger(__name__),
                per_candidate_timeout_seconds=420.0,
                minimum_timeout_seconds=420.0,
            )

        parallel = ResilientBatchEvaluator(
            preferred_factory=_parallel_factory,
            fallback_factory=lambda: local,
            description="portfolio synergy parallel evaluator",
            logger=logging.getLogger(__name__),
        )
        return CachedBatchEvaluator(
            parallel,
            cache=self._score_cache,
            metrics_cache=self._metrics_cache,
            signature_prefix=f"{self.name}:parallel:{evaluation_key}",
        )

    def compute_final_metrics(self, mutations: dict[str, Any]) -> dict[str, Any]:
        cache_key = mutation_signature(mutations)
        cached = self._metrics_cache.get(cache_key)
        if cached is not None and "strategy_summary" in cached:
            return self._with_replay_metadata(dict(cached))
        _, _, metrics = _evaluate(
            self._replay_data(),
            mutations,
            equity=self.initial_equity,
            data_dir=self.data_dir,
        )
        metrics = self._with_replay_metadata(metrics)
        self._metrics_cache[cache_key] = dict(metrics)
        return metrics

    def run_phase_diagnostics(
        self,
        phase: int,
        state,
        metrics: dict[str, Any],
        greedy_result: GreedyResult,
    ) -> str:
        del state
        return _format_phase_diagnostics(phase, metrics, greedy_result, enhanced=False)

    def run_enhanced_diagnostics(
        self,
        phase: int,
        state,
        metrics: dict[str, Any],
        greedy_result: GreedyResult,
    ) -> str:
        del state
        return _format_phase_diagnostics(phase, metrics, greedy_result, enhanced=True)

    def build_end_of_round_artifacts(self, state) -> EndOfRoundArtifacts:
        metrics = self.compute_final_metrics(state.cumulative_mutations)
        diagnostics = _format_final_diagnostics(metrics)
        return EndOfRoundArtifacts(
            final_diagnostics_text=diagnostics,
            dimension_reports={
                "round_design": json.dumps(
                    _round_design_record(
                        self.base_source,
                        source_fingerprint=self._ensure_bundle().cache_source_fingerprint,
                    ),
                    indent=2,
                    default=_json_default,
                )
            },
            overall_verdict=(
                "Promote only after a fresh holdout or walk-forward replay confirms the "
                "static-risk alpha and trade-frequency gains without DD expansion."
            ),
        )

    def _replay_data(self):
        return self._ensure_bundle().data

    def _ensure_bundle(self) -> ReplayBundle[UnifiedPortfolioData]:
        source_fingerprint = stable_signature(
            {
                "data_tree": fingerprint_tree(self.data_dir, patterns=("*.parquet",), recursive=False),
                "strategy_configs": fingerprint_paths(PHASE_SOURCE_CONFIGS.values(), root=ROOT),
                "initial_mutations": stable_signature(self.initial_mutations),
                "base_source": self.base_source,
                "initial_equity": self.initial_equity,
                "score_profile": SCORE_PROFILE,
                "return_basis": OPTIMIZATION_RETURN_BASIS,
                "risk_stance": RISK_STANCE,
            }
        )
        cache_key = build_cache_key(
            "swing.portfolio_synergy.replay_bundle",
            source_fingerprint=source_fingerprint,
            extra={
                "data_dir": str(self.data_dir.resolve()),
                "initial_equity": self.initial_equity,
                "round": ROUND_NAME,
            },
        )
        if self._cached_bundle is not None and self._cached_bundle.cache_key == cache_key:
            return self._cached_bundle
        if self._cache_source_fingerprint and self._cache_source_fingerprint != source_fingerprint:
            self._metrics_cache.clear()
            self._score_cache.clear()
        seed_config = UnifiedBacktestConfig(initial_equity=self.initial_equity, data_dir=self.data_dir)
        self._data = load_unified_data(seed_config)
        self._cached_bundle = ReplayBundle(
            data=self._data,
            cache_key=cache_key,
            cache_source_fingerprint=source_fingerprint,
        )
        self._cache_source_fingerprint = source_fingerprint
        return self._cached_bundle

    def _with_replay_metadata(self, metrics: dict[str, Any]) -> dict[str, Any]:
        bundle = self._ensure_bundle()
        metrics.update(
            {
                "replay_architecture": REPLAY_ARCHITECTURE,
                "replay_source_fingerprint": bundle.cache_source_fingerprint,
                "replay_cache_key": bundle.cache_key,
                "live_swing_risk_adapter": LIVE_SWING_RISK_ADAPTER,
                "live_portfolio_rule_checker": LIVE_PORTFOLIO_RULE_CHECKER,
                "live_strategy_coordinator": LIVE_STRATEGY_COORDINATOR,
                "portfolio_replay_scope": PORTFOLIO_REPLAY_SCOPE,
                "risk_basis": "static_initial_strategy_risk_headline_with_mtm_drawdown",
                "source_strategy_artifacts": _source_artifact_records(),
                "thin_layer_assessment": THIN_LAYER_ASSESSMENT,
            }
        )
        return metrics

    @staticmethod
    def _gate_criteria(metrics: dict[str, Any]) -> list[GateCriterion]:
        strategy_summary = metrics.get("strategy_summary", {}) or {}
        strategy_trades = [
            float((strategy_summary.get(sid, {}) or {}).get("trades", 0.0) or 0.0)
            for sid in PHASE_SCORING_KWARGS["required_strategies"]
        ]
        static_pnls = [
            max(float((strategy_summary.get(sid, {}) or {}).get("static_risk_pnl", 0.0) or 0.0), 0.0)
            for sid in PHASE_SCORING_KWARGS["required_strategies"]
        ]
        positive_total = sum(static_pnls)
        single_share = max(static_pnls) / positive_total if positive_total > 0 else 1.0
        min_strategy_trades = min(strategy_trades) if strategy_trades else 0.0
        return [
            GateCriterion("net_return_pct", 250.0, float(metrics.get("net_return_pct", 0.0)), float(metrics.get("net_return_pct", 0.0)) >= 250.0),
            GateCriterion("total_trades", float(PHASE_SCORING_KWARGS["min_trades"]), float(metrics.get("total_trades", 0.0)), float(metrics.get("total_trades", 0.0)) >= float(PHASE_SCORING_KWARGS["min_trades"])),
            GateCriterion("profit_factor", float(PHASE_SCORING_KWARGS["min_profit_factor"]), float(metrics.get("profit_factor", 0.0)), float(metrics.get("profit_factor", 0.0)) >= float(PHASE_SCORING_KWARGS["min_profit_factor"])),
            GateCriterion("max_drawdown_pct", float(PHASE_SCORING_KWARGS["max_drawdown_hard_pct"]) * 100.0, float(metrics.get("max_drawdown_pct", 0.0)), float(metrics.get("max_drawdown_pct", 0.0)) <= float(PHASE_SCORING_KWARGS["max_drawdown_hard_pct"]) * 100.0),
            GateCriterion("min_strategy_trades", float(PHASE_SCORING_KWARGS["min_required_strategy_trades"]), min_strategy_trades, min_strategy_trades >= float(PHASE_SCORING_KWARGS["min_required_strategy_trades"])),
            GateCriterion("max_single_strategy_static_pnl_share", float(PHASE_SCORING_KWARGS["max_single_strategy_static_pnl_share"]), single_share, single_share <= float(PHASE_SCORING_KWARGS["max_single_strategy_static_pnl_share"])),
        ]


def _phase_diagnostic_gaps(_phase: int, metrics: dict[str, Any]) -> list[str]:
    gaps: list[str] = []
    if float(metrics.get("max_drawdown_pct", 0.0)) > 14.0:
        gaps.append("Drawdown is near the controlled-aggressive ceiling; prefer dynamic risk sizing or overlay scale-down before adding heat.")
    if float(metrics.get("total_trades", 0.0)) < float(PHASE_SCORING_KWARGS["min_trades"]):
        gaps.append("Trade frequency remains below target; inspect whether blocked heat is suppressing a useful sleeve.")
    if float(metrics.get("profit_factor", 0.0)) < float(PHASE_SCORING_KWARGS["min_profit_factor"]):
        gaps.append("Profit factor is below the alpha-quality gate; avoid accepting frequency-only candidates.")
    strategy_summary = metrics.get("strategy_summary", {}) or {}
    for sid in PHASE_SCORING_KWARGS["required_strategies"]:
        trades = float((strategy_summary.get(sid, {}) or {}).get("trades", 0.0) or 0.0)
        if trades < float(PHASE_SCORING_KWARGS["min_required_strategy_trades"]):
            gaps.append(f"{sid} participation is below floor; rebalance risk allocation before adding more filters.")
    return gaps


def _format_phase_diagnostics(
    phase: int,
    metrics: dict[str, Any],
    greedy_result: GreedyResult,
    *,
    enhanced: bool,
) -> str:
    lines = [
        f"SWING PORTFOLIO SYNERGY PHASE {phase} DIAGNOSTICS",
        "=" * 70,
        f"Score: {greedy_result.base_score:.4f} -> {greedy_result.final_score:.4f}",
        f"Kept: {', '.join(greedy_result.kept_features) if greedy_result.kept_features else '(none)'}",
        f"Comparable return: {metrics.get('net_return_pct', 0.0):+.2f}%",
        f"Compounded MTM return: {metrics.get('compounded_mtm_net_return_pct', 0.0):+.2f}%",
        f"Max DD: {metrics.get('max_drawdown_pct', 0.0):.2f}%",
        f"PF: {metrics.get('profit_factor', 0.0):.2f}",
        f"Trades: {metrics.get('total_trades', 0)}",
        f"Heat max: {metrics.get('heat_max_R', 0.0):.2f}R",
        "",
        "Per Strategy",
    ]
    for sid, strat in (metrics.get("strategy_summary", {}) or {}).items():
        lines.append(
            f"  {sid:<10} trades={strat.get('trades', 0):>4} "
            f"signals={strat.get('entry_signals_fired', 0):>4} "
            f"requests={strat.get('entry_requests', strat.get('entry_signals_fired', 0)):>4} "
            f"accepted={strat.get('entries_accepted', 0):>4} "
            f"blocked={strat.get('entries_blocked', 0):>4} "
            f"suppressed={strat.get('suppressed_entry_retries', 0):>4} "
            f"static_pnl=${strat.get('static_risk_pnl', 0.0):+,.2f}"
        )
    if enhanced and metrics.get("block_reason_summary"):
        lines.extend(["", "Block Reasons"])
        for sid, reasons in metrics["block_reason_summary"].items():
            reason_text = ", ".join(f"{reason}: {count}" for reason, count in sorted(reasons.items()))
            lines.append(f"  {sid:<10} {reason_text}")
    return "\n".join(lines) + "\n"


def _format_final_diagnostics(metrics: dict[str, Any]) -> str:
    round_label = ROUND_NAME.replace("_", " ").upper()
    lines = [
        f"SWING PORTFOLIO SYNERGY {round_label} FINAL DIAGNOSTICS",
        "=" * 70,
        f"Initial equity: ${metrics.get('initial_equity', STARTING_EQUITY):,.0f}",
        f"Risk stance: {RISK_STANCE}",
        f"Score profile: {SCORE_PROFILE}",
        f"Return basis: {metrics.get('return_basis', OPTIMIZATION_RETURN_BASIS)}",
        f"Replay architecture: {metrics.get('replay_architecture', REPLAY_ARCHITECTURE)}",
        f"Replay source fingerprint: {metrics.get('replay_source_fingerprint', '')}",
        "",
        "Headline",
        f"  Comparable net return: {metrics.get('net_return_pct', 0.0):+.2f}%",
        f"  Comparable net PnL:    ${metrics.get('net_pnl', 0.0):+,.2f}",
        f"  Compounded MTM return: {metrics.get('compounded_mtm_net_return_pct', 0.0):+.2f}%",
        f"  Max DD:                {metrics.get('max_drawdown_pct', 0.0):.2f}%",
        f"  PF:                    {metrics.get('profit_factor', 0.0):.2f}",
        f"  Trades:                {metrics.get('total_trades', 0)}",
        f"  Max heat:              {metrics.get('heat_max_R', 0.0):.2f}R",
        f"  Portfolio rule blocks: {metrics.get('portfolio_rule_block_events', 0)}",
        f"  Portfolio size events: {metrics.get('portfolio_rule_sizing_events', 0)}",
        "",
        "Per Strategy",
    ]
    for sid, strat in (metrics.get("strategy_summary", {}) or {}).items():
        lines.append(
            f"  {sid:<10} trades={strat.get('trades', 0):>4} "
            f"signals={strat.get('entry_signals_fired', 0):>4} "
            f"requests={strat.get('entry_requests', strat.get('entry_signals_fired', 0)):>4} "
            f"accepted={strat.get('entries_accepted', 0):>4} "
            f"blocked={strat.get('entries_blocked', 0):>4} "
            f"suppressed={strat.get('suppressed_entry_retries', 0):>4} "
            f"static_pnl=${strat.get('static_risk_pnl', 0.0):+,.2f}"
        )
    if metrics.get("block_reason_summary"):
        lines.extend(["", "Block Reasons"])
        for sid, reasons in metrics["block_reason_summary"].items():
            reason_text = ", ".join(f"{reason}: {count}" for reason, count in sorted(reasons.items()))
            lines.append(f"  {sid:<10} {reason_text}")
    lines.extend(
        [
            "",
            "Existing Safeguards",
            f"  Swing heat adapter: {metrics.get('live_swing_risk_adapter', LIVE_SWING_RISK_ADAPTER)}",
            f"  Portfolio rule checker: {metrics.get('live_portfolio_rule_checker', LIVE_PORTFOLIO_RULE_CHECKER)}",
            "  Completed-bar policy: ATRSS uses RTH hourly data; Helix uses raw hourly/4h/daily maps; TPC uses completed 15m/30m/1h/4h/daily maps.",
            "  Risk basis: static initial strategy-risk returns for selection, MTM equity for drawdown.",
            f"  Replay scope: {metrics.get('portfolio_replay_scope', PORTFOLIO_REPLAY_SCOPE)}",
            "  Thin-layer status: portfolio risk is mostly thin over live risk; TPC source replay is thin; ATRSS and Helix still need shared-core migration.",
            "  Artifact lineage: source optimized-config and diagnostics hashes are emitted in source_strategy_artifacts.",
            "  TPC caveat: completed-trade replay validates portfolio admission/sizing only; source execution integrity remains owned by the TPC source replay diagnostics.",
            "  Migration gate: do not promote ATRSS/Helix portfolio results as full live/backtest parity until engine-owned candidate/order/exit decisions are in shared cores.",
        ]
    )
    return "\n".join(lines) + "\n"


def _resolve_initial_mutations(base_config: str | None) -> tuple[dict[str, Any], str]:
    if base_config:
        base_path = Path(base_config)
        if not base_path.is_absolute():
            base_path = ROOT / base_path
        return json.loads(base_path.read_text()), str(base_path)
    return phase_latest_strategy_mutations(), "phase_source_configs_atrss_round_3_helix_round_5"


def build_phase_runner(args: argparse.Namespace) -> PhaseRunner:
    data_dir = Path(args.data_dir)
    if not data_dir.is_absolute():
        data_dir = ROOT / data_dir
    initial_mutations, base_source = _resolve_initial_mutations(getattr(args, "base_config", None))
    manager = RoundManager("swing", "portfolio_synergy")
    plugin = PortfolioSynergyPhasePlugin(
        data_dir,
        initial_equity=float(args.equity),
        max_workers=int(args.max_workers),
        initial_mutations=initial_mutations,
        base_source=base_source,
    )
    round_num, round_dir = manager.resolve_round(
        getattr(args, "round", 1),
        for_write=True,
        expected_phases=plugin.num_phases,
    )
    if round_num != 1:
        raise ValueError("Portfolio synergy phase auto must start as round_1 for this optimisation design.")
    return PhaseRunner(
        plugin=plugin,
        output_dir=round_dir,
        round_name="Swing portfolio synergy round 1 phase auto",
        max_rounds=getattr(args, "max_rounds", 12),
        min_delta=getattr(args, "min_delta", 0.001),
        max_retries=getattr(args, "max_retries", 2),
        round_manager=manager,
        round_num=round_num,
    )


def run_phase_auto(args: argparse.Namespace) -> Path:
    runner = build_phase_runner(args)
    state = runner.run_all_phases(start_phase=getattr(args, "start_phase", None))
    print(f"\nPhase-auto synergy round 1 complete: {runner.output_dir}", flush=True)
    print(f"Completed phases: {state.completed_phases}", flush=True)
    return runner.output_dir


def _round_design_record(base_source: str, *, source_fingerprint: str = "") -> dict[str, Any]:
    return {
        "family": "swing",
        "strategy": "portfolio_synergy",
        "round": ROUND_NAME,
        "base_config": base_source,
        "source_strategy_configs": {sid: str(path) for sid, path in PHASE_SOURCE_CONFIGS.items()},
        "source_strategy_artifacts": _source_artifact_records(),
        "source_fingerprint": source_fingerprint,
        "initial_equity": STARTING_EQUITY,
        "risk_stance": RISK_STANCE,
        "score_profile": SCORE_PROFILE,
        "return_basis": OPTIMIZATION_RETURN_BASIS,
        "replay_architecture": REPLAY_ARCHITECTURE,
        "thin_layer_assessment": THIN_LAYER_ASSESSMENT,
        "live_parity_contract": {
            "swing_heat_adapter": LIVE_SWING_RISK_ADAPTER,
            "portfolio_rule_checker": LIVE_PORTFOLIO_RULE_CHECKER,
            "strategy_coordinator": LIVE_STRATEGY_COORDINATOR,
            "cache_fingerprint_policy": (
                "Replay and evaluation cache keys include data tree metadata, source strategy config paths, "
                "initial mutations, starting equity, risk stance, score profile, return basis, and phase scoring gates."
            ),
        },
        "known_execution_assumptions": [
            "ATRSS and AKC Helix are source-engine bar replays rather than independent trade recombination, but they are not yet optimal thin wrappers over shared cores.",
            "TPC source trades are generated by the shared ETF source replay first, then re-admitted through the family portfolio replay as sizing/admission evidence.",
            "Portfolio headline returns are static initial-risk comparable returns; compounded MTM is reported separately.",
        ],
        "scoring_kwargs": PHASE_SCORING_KWARGS,
        "diagnostic_assessments": DIAGNOSTIC_ASSESSMENTS,
        "phases": [
            {
                "phase": idx,
                "name": name,
                "candidate_count": len(candidates),
                "candidate_names": [candidate_name for candidate_name, _ in candidates],
            }
            for idx, (name, candidates) in enumerate(PHASES, start=1)
        ],
        "anti_overfit_policy": [
            "Start from full latest individual artifacts rather than tuning a tiny holdout slice.",
            "Score comparable static-initial-risk returns so late compounding cannot dominate selection.",
            "Keep alpha/frequency targets above the incumbent so candidates remain distinguishable.",
            "Require all active swing strategies to clear a 25-trade liveness floor; reward, but do not hard-force, higher sleeve balance and frequency.",
            "Prefer structural risk, heat, priority, and broad quality gates over narrow post-hoc signal filters.",
            "Reject any blend above 16% max DD and stop rewarding extra conservatism once DD is below 11.5%.",
        ],
        "artifact_hygiene_policy": [
            "Round metadata records source optimized-config hashes and diagnostic summary hashes.",
            "Replay/evaluation cache fingerprints include source artifact paths, data tree metadata, equity, risk stance, score profile, and return basis.",
            "Candidate/completed-trade replay is labeled as portfolio replay evidence and must not be promoted as fresh source execution validation.",
            "Source strategy timing/fill/cost changes require regenerating source diagnostics before promotion.",
        ],
    }


def phase_latest_strategy_mutations() -> dict[str, Any]:
    """Load latest phase-auto source configs, with ATRSS pinned to round 3."""

    mutations = dict(LIVE_SEED_MUTATIONS)

    atrss = _load_json(PHASE_SOURCE_CONFIGS["ATRSS"])
    for key, value in atrss.items():
        if key.startswith("flags."):
            mutations[f"atrss_flags.{key.split('.', 1)[1]}"] = value
        elif key.startswith("param_overrides."):
            mutations[f"atrss_param.{key.split('.', 1)[1]}"] = value
        elif key == "fixed_qty" and value is not None:
            mutations["fixed_qty"] = value

    helix = _load_json(PHASE_SOURCE_CONFIGS["AKC_HELIX"])
    for key, value in helix.items():
        if key.startswith("flags."):
            mutations[f"helix_flags.{key.split('.', 1)[1]}"] = value
        elif key.startswith("param_overrides."):
            mutations[f"helix_param.{key.split('.', 1)[1]}"] = value

    tpc = _load_json(PHASE_SOURCE_CONFIGS["TPC"])
    for key, value in tpc.items():
        mutations[f"tpc_param.{key}"] = value

    return mutations


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _metric_value(summary: dict[str, Any], key: str) -> Any:
    headline = summary.get("headline_metrics", {}) or {}
    final = summary.get("final_metrics", {}) or {}
    aliases = {
        "max_drawdown_pct": ("max_drawdown_pct", "max_dd_pct"),
        "sharpe": ("sharpe", "sharpe_ratio"),
        "calmar": ("calmar", "calmar_ratio"),
    }
    for candidate in aliases.get(key, (key,)):
        if candidate in headline:
            return headline[candidate]
        if candidate in final:
            return final[candidate]
        if candidate in summary:
            return summary[candidate]
    if key in summary:
        return summary[key]
    if key in headline:
        return headline[key]
    return final.get(key)


def _source_artifact_records() -> dict[str, dict[str, Any]]:
    records: dict[str, dict[str, Any]] = {}
    for sid, config_path in PHASE_SOURCE_CONFIGS.items():
        record: dict[str, Any] = {
            "optimized_config_path": str(config_path),
            "optimized_config_sha256": _file_sha256(config_path) if config_path.exists() else "",
            "diagnostic_scope": PHASE_SOURCE_SCOPES.get(sid, ""),
        }
        diagnostic_path = PHASE_SOURCE_DIAGNOSTICS.get(sid)
        if diagnostic_path is not None:
            record["diagnostic_summary_path"] = str(diagnostic_path)
            record["diagnostic_summary_sha256"] = (
                _file_sha256(diagnostic_path) if diagnostic_path.exists() else ""
            )
            if diagnostic_path.exists():
                summary = _load_json(diagnostic_path)
                provenance = summary.get("provenance") or {}
                record["diagnostic_metrics"] = {
                    key: _metric_value(summary, key)
                    for key in (
                        "total_trades",
                        "total_r",
                        "net_return_pct",
                        "profit_factor",
                        "max_drawdown_pct",
                        "sharpe",
                        "initial_equity",
                    )
                    if _metric_value(summary, key) is not None
                }
                record["provenance_status"] = summary.get("provenance_status")
                record["selection_status"] = summary.get("selection_status")
                record["selection_fingerprint"] = provenance.get("selection_fingerprint")
                record["diagnostics_fingerprint"] = provenance.get("diagnostics_fingerprint")
                if summary.get("diagnostics_refresh"):
                    record["diagnostics_refresh"] = summary["diagnostics_refresh"]
                generated_at = summary.get("generated_at_utc")
                if generated_at is not None:
                    record["diagnostic_generated_at_utc"] = generated_at
        records[sid] = record
    return records


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def _write_final_report(path: Path, summary: dict[str, Any]) -> None:
    metrics = summary["final_metrics"]
    lines = [
        f"SWING PORTFOLIO SYNERGY {summary['round'].upper()}",
        "=" * 70,
        f"Initial equity: ${summary['initial_equity']:,.0f}",
        f"Risk stance:    {summary['risk_stance']}",
        f"Score profile: {summary['score_profile']}",
        f"Return basis:  {summary['return_basis']}",
        "DD guardrail:  hard reject above 16%; no extra score below 11.5%",
        "Design note:   alpha/frequency lead the score; all three swing sleeves must stay active.",
        "",
        "Phases",
    ]
    for phase in summary["phases"]:
        phase_metrics = phase["metrics"]
        lines.append(
            f"  {phase['phase']}. {phase['name']}: score {phase['base_score']:.4f} -> "
            f"{phase['final_score']:.4f}, kept={phase['kept_features'] or []}, "
            f"ret={phase_metrics['net_return_pct']:+.2f}%, "
            f"DD={phase_metrics['max_drawdown_pct']:.2f}%, "
            f"trades={phase_metrics['total_trades']}"
        )
    lines.extend(
        [
            "",
            "Final Metrics",
            f"  Comparable net return: {metrics['net_return_pct']:+.2f}%",
            f"  Comparable net PnL:    ${metrics['net_pnl']:+,.2f}",
            f"  Compounded MTM return: {metrics['compounded_mtm_net_return_pct']:+.2f}%",
            f"  Max DD:                {metrics['max_drawdown_pct']:.2f}%",
            f"  Sharpe:                {metrics['sharpe']:.2f}",
            f"  PF:                    {metrics['profit_factor']:.2f}",
            f"  Trades:                {metrics['total_trades']}",
            f"  Overlay PnL:           ${metrics['overlay_pnl']:+,.2f}",
            "",
            "Per Strategy",
        ]
    )
    for sid, strat in metrics["strategy_summary"].items():
        lines.append(
            f"  {sid:<10} trades={strat['trades']:>4} "
            f"static_pnl=${strat.get('static_risk_pnl', 0.0):+,.2f} "
            f"portfolio_pnl=${strat['pnl']:+,.2f} "
            f"signals={strat.get('entry_signals_fired', 0)} "
            f"requests={strat.get('entry_requests', strat.get('entry_signals_fired', 0))} "
            f"accepted={strat['entries_accepted']} blocked={strat['entries_blocked']} "
            f"suppressed={strat.get('suppressed_entry_retries', 0)}"
        )
    if metrics.get("block_reason_summary"):
        lines.extend(["", "Block Reasons"])
        for sid, reasons in metrics["block_reason_summary"].items():
            reason_text = ", ".join(f"{reason}: {count}" for reason, count in sorted(reasons.items()))
            lines.append(f"  {sid:<10} {reason_text}")
    path.write_text("\n".join(lines) + "\n")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-config",
        default=None,
        help="Optional optimized_config.json to continue from; defaults to latest individual strategy artifacts.",
    )
    parser.add_argument("--data-dir", default=ROOT / "backtests" / "swing" / "data" / "raw")
    parser.add_argument("--equity", type=float, default=STARTING_EQUITY)
    parser.add_argument("--max-workers", type=int, default=2)
    parser.add_argument("--round", type=int, default=1)
    parser.add_argument("--start-phase", type=int, default=None)
    parser.add_argument("--max-rounds", type=int, default=12)
    parser.add_argument("--min-delta", type=float, default=0.001)
    parser.add_argument("--max-retries", type=int, default=2)
    parser.add_argument("--output-root", default=None, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    if args.output_root:
        print("Ignoring --output-root; standard phased auto output uses backtests/output/swing/portfolio_synergy/round_1.", flush=True)
    run_phase_auto(args)


if __name__ == "__main__":
    main()
