from __future__ import annotations

from backtests.auto.shared.types import Experiment


BASE_MUTATIONS = {
    "kalcb.session.opening_range_bars": 6,
    "kalcb.session.flatten_time": "15:15",
    "kalcb.session.entry_window_start": "10:25",
    "kalcb.session.entry_window_end": "13:00",
    "kalcb.session.ws_budget": 8,
    "kalcb.frontier.enabled": True,
    "kalcb.frontier.size": 103,
    "kalcb.frontier.selection_mode": "opportunity",
    "kalcb.frontier.active_selection_mode": "liquidity",
    "kalcb.frontier.rest_safety_fraction": 0.50,
    "kalcb.frontier.shadow_enabled": True,
    "kalcb.frontier.shadow_max_positions": 128,
    "kalcb.frontier.rotation_enabled": True,
    "kalcb.frontier.rotation_slots": 2,
    "kalcb.frontier.rotation_min_shadow_trades": 2,
    "kalcb.frontier.rotation_min_avg_r": 0.05,
    "kalcb.frontier.rotation_min_total_r": 0.0,
    "kalcb.frontier.rotation_min_frontier_trades": 40,
    "kalcb.frontier.rotation_min_frontier_avg_r": 0.05,
    "kalcb.frontier.rotation_min_frontier_total_r": 2.0,
    "kalcb.frontier.rotation_min_proof_symbols": 2,
    "kalcb.entry.rvol_threshold": 2.0,
    "kalcb.entry.rvol_max": 5.0,
    "kalcb.entry.cpr_relax_threshold": 0.55,
    "kalcb.entry.cpr_relax_min_score": 4,
    "kalcb.entry.or_width_min_pct": 0.0015,
    "kalcb.entry.breakout_distance_cap_r": 1.0,
    "kalcb.entry.orb_entry_range_cap_r": 1.1,
    "kalcb.entry.combined_breakout_score_min": 5,
    "kalcb.entry.combined_breakout_min_rvol": 2.5,
    "kalcb.entry.combined_avwap_cap_pct": 0.003,
    "kalcb.entry.pdh_avwap_cap_pct": 0.005,
    "kalcb.entry.or_caution_window_start": "10:30",
    "kalcb.entry.or_caution_window_end": "11:30",
    "kalcb.entry.or_caution_min_rvol": 3.0,
    "kalcb.entry.block_combined_regime_b": True,
    "kalcb.entry.entry_score_blocklist": ["KRX_COMBINED_BREAKOUT:5"],
    "kalcb.risk.stop_atr_multiple": 0.8,
    "kalcb.risk.pdh_size_mult": 0.75,
    "kalcb.risk.regime_mult_b": 0.7,
    "kalcb.exit.use_partial_takes": False,
    "kalcb.exit.partial_r_trigger": 0.6,
    "kalcb.exit.partial_fraction": 0.4,
    "kalcb.exit.partial_stop_to_breakeven": True,
    "kalcb.exit.partial_breakeven_buffer_r": 0.1,
    "kalcb.exit.quick_exit_enabled": True,
    "kalcb.exit.quick_exit_bars": 10,
    "kalcb.exit.quick_exit_min_r": -0.5,
    "kalcb.exit.failure_stop_enabled": False,
    "kalcb.exit.failure_stop_bars": 10,
    "kalcb.exit.failure_stop_mfe_max_r": 0.2,
    "kalcb.exit.failure_stop_current_r_max": 0.0,
    "kalcb.exit.failure_stop_to_r": -0.25,
    "kalcb.exit.mfe_conviction_enabled": True,
    "kalcb.exit.mfe_conviction_check_bars": 16,
    "kalcb.exit.mfe_conviction_min_r": 0.2,
    "kalcb.exit.mfe_conviction_floor_r": -0.15,
    "kalcb.exit.adaptive_trail_start_bars": 30,
    "kalcb.exit.adaptive_trail_tighten_bars": 25,
    "kalcb.exit.adaptive_trail_late_activate_r": 0.3,
    "kalcb.exit.adaptive_trail_late_distance_r": 0.18,
    "kalcb.exit.flow_reversal_enabled": True,
    "kalcb.exit.flow_reversal_min_hold_bars": 12,
    "kalcb.exit.flow_reversal_cpr_threshold": 0.3,
    "kalcb.exit.flow_reversal_mfe_grace_r": 0.2,
    "kalcb.exit.flow_reversal_trailing_activate_r": 0.0,
    "kalcb.carry.mode": "shadow",
    "kalcb.carry.min_cpr": 0.6,
    "kalcb.carry.min_r": 0.5,
}

PHASE_FOCUS = {
    1: ("frequency expansion through causal windows and strict secondary websocket ranks", ["entry_count", "expected_total_r", "avg_r"]),
    2: ("route-aware discrimination for marginal OR and score cohorts", ["expected_total_r", "avg_r", "profit_factor"]),
    3: ("interaction probes for frequency plus quality gates", ["entry_count", "expected_total_r", "profit_factor"]),
    4: ("exit and hold management for weak launches and winner capture", ["mfe_capture", "expected_total_r", "avg_r"]),
    5: ("aggressive-but-capped sizing and capacity after quality controls", ["official_mtm_net_return_pct", "expected_total_r", "max_drawdown_pct"]),
    6: ("cost, carry, and final robustness hygiene", ["profit_factor", "official_mtm_net_return_pct", "same_bar_fill_count"]),
}


def get_phase_candidates(phase: int) -> list[Experiment]:
    raw = {
        1: [
            ("ws10_secondary_strict", {"kalcb.session.ws_budget": 10, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.0, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30"}),
            ("ws12_secondary_strict", {"kalcb.session.ws_budget": 12, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.2, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30"}),
            ("entry_start1010_mid_confirm", {"kalcb.session.entry_window_start": "10:10", "kalcb.entry.or_caution_window_start": "10:10", "kalcb.entry.or_caution_window_end": "11:30", "kalcb.entry.or_caution_min_rvol": 2.8, "kalcb.entry.or_caution_require_two_close": True}),
            ("entry_start1000_hot_only", {"kalcb.session.entry_window_start": "10:00", "kalcb.entry.or_caution_window_start": "10:00", "kalcb.entry.or_caution_window_end": "11:30", "kalcb.entry.or_caution_min_rvol": 3.2, "kalcb.entry.or_caution_require_two_close": True}),
            ("entry_end1330", {"kalcb.session.entry_window_end": "13:30"}),
            ("pdh_window1300", {"kalcb.entry.pdh_entry_window_end": "13:00"}),
        ],
        2: [
            ("score3_block", {"kalcb.entry.entry_score_blocklist": ["KRX_COMBINED_BREAKOUT:5", "KRX_OR_BREAKOUT:3", "KRX_PDH_BREAKOUT:3"]}),
            ("score3_half", {"kalcb.entry.entry_score_blocklist": ["KRX_COMBINED_BREAKOUT:5"], "kalcb.entry.entry_score_size_mults": {"KRX_OR_BREAKOUT:3": 0.5, "KRX_PDH_BREAKOUT:3": 0.5}}),
            ("or_rvol25", {"kalcb.entry.or_breakout_min_rvol": 2.5}),
            ("or_rvol30", {"kalcb.entry.or_breakout_min_rvol": 3.0}),
            ("mid_or_off", {"kalcb.entry.or_caution_min_rvol": 0.0}),
            ("mid_or_rvol28", {"kalcb.entry.or_caution_min_rvol": 2.8}),
            ("mid_or_rvol30", {"kalcb.entry.or_caution_min_rvol": 3.0}),
            ("mid_or_rvol32", {"kalcb.entry.or_caution_min_rvol": 3.2}),
            ("mid_or_two_close", {"kalcb.entry.or_caution_require_two_close": True}),
            ("mid_or_avwap100bps", {"kalcb.entry.or_caution_max_avwap_dist_pct": 0.010}),
            ("pdh_rvol18", {"kalcb.entry.pdh_breakout_min_rvol": 1.8}),
        ],
        3: [
            ("ws10_sec_mid_rvol30", {"kalcb.session.ws_budget": 10, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.0, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30", "kalcb.entry.or_caution_min_rvol": 3.0}),
            ("ws12_sec_or_rvol25", {"kalcb.session.ws_budget": 12, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.2, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30", "kalcb.entry.or_breakout_min_rvol": 2.5}),
            ("start1010_ws10_secondary", {"kalcb.session.entry_window_start": "10:10", "kalcb.session.ws_budget": 10, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.0, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30", "kalcb.entry.or_caution_window_start": "10:10", "kalcb.entry.or_caution_window_end": "11:30", "kalcb.entry.or_caution_min_rvol": 3.0, "kalcb.entry.or_caution_require_two_close": True}),
            ("late1330_pdh1300", {"kalcb.session.entry_window_end": "13:30", "kalcb.entry.pdh_entry_window_end": "13:00"}),
            ("pdh_looser_avwap_late", {"kalcb.entry.pdh_entry_window_end": "13:30", "kalcb.entry.pdh_avwap_cap_pct": 0.0075}),
            ("or_gap_half", {"kalcb.entry.entry_detail_size_mults": {"KRX_OR_BREAKOUT:*:!gap_up": 0.5}}),
        ],
        4: [
            ("partial_off", {"kalcb.exit.use_partial_takes": False}),
            ("partial_050_33pct", {"kalcb.exit.partial_r_trigger": 0.5, "kalcb.exit.partial_fraction": 0.33}),
            ("partial_080_33pct", {"kalcb.exit.partial_r_trigger": 0.8, "kalcb.exit.partial_fraction": 0.33}),
            ("partial_no_be", {"kalcb.exit.partial_stop_to_breakeven": False}),
            ("failure_stop_8_n020", {"kalcb.exit.failure_stop_bars": 8, "kalcb.exit.failure_stop_to_r": -0.20, "kalcb.exit.failure_stop_mfe_max_r": 0.15}),
            ("failure_stop_off", {"kalcb.exit.failure_stop_enabled": False}),
            ("mfe_conviction_on", {"kalcb.exit.mfe_conviction_enabled": True}),
            ("flow_reversal_on", {"kalcb.exit.flow_reversal_enabled": True}),
            ("adaptive_earlier_tight", {"kalcb.exit.adaptive_trail_start_bars": 24, "kalcb.exit.adaptive_trail_late_activate_r": 0.12, "kalcb.exit.adaptive_trail_late_distance_r": 0.18}),
            ("adaptive_later_loose", {"kalcb.exit.adaptive_trail_start_bars": 30, "kalcb.exit.adaptive_trail_late_activate_r": 0.30, "kalcb.exit.adaptive_trail_late_distance_r": 0.18}),
        ],
        5: [
            ("pdh_full_size", {"kalcb.risk.pdh_size_mult": 1.0}),
            ("pdh_125_size", {"kalcb.risk.pdh_size_mult": 1.25}),
            ("risk_0012_cap10", {"kalcb.risk.risk_per_trade_pct": 0.0012, "kalcb.risk.max_position_notional_pct": 0.10}),
            ("risk_0015_cap10", {"kalcb.risk.risk_per_trade_pct": 0.0015, "kalcb.risk.max_position_notional_pct": 0.10}),
            ("risk_0012_cap12_hot8", {"kalcb.risk.risk_per_trade_pct": 0.0012, "kalcb.risk.max_position_notional_pct": 0.12, "kalcb.risk.max_positions": 8, "kalcb.risk.heat_cap_r": 5.0}),
            ("ws10_secondary_hot8", {"kalcb.session.ws_budget": 10, "kalcb.risk.max_positions": 8, "kalcb.risk.heat_cap_r": 5.0, "kalcb.entry.secondary_rank_start": 9, "kalcb.entry.secondary_min_rvol": 3.0, "kalcb.entry.secondary_min_score": 4, "kalcb.entry.secondary_require_pdh_or_late": True, "kalcb.entry.secondary_late_time": "11:30"}),
            ("or5_no_barvol_half", {"kalcb.entry.entry_detail_size_mults": {"KRX_OR_BREAKOUT:5:!bar_vol_surge": 0.5}}),
        ],
        6: [
            ("carry_off", {"kalcb.carry.mode": "off"}),
            ("slippage_5bps", {"kalcb.robustness.slippage_bps": 5.0}),
            ("slippage_8bps", {"kalcb.robustness.slippage_bps": 8.0}),
            ("rvol_cap55", {"kalcb.entry.rvol_max": 5.5}),
            ("rvol_cap65", {"kalcb.entry.rvol_max": 6.5}),
            ("quick_exit_slower", {"kalcb.exit.quick_exit_bars": 12, "kalcb.exit.quick_exit_min_r": -0.6}),
        ],
    }.get(phase, [])
    return [Experiment(name, mutations) for name, mutations in raw]
