"""Static S&P 500 constituents for the IARIC research pipeline.

Each entry is (symbol, sector, primary_exchange).
Update quarterly when the S&P index rebalances.
"""

from __future__ import annotations

SP500_CONSTITUENTS: list[tuple[str, str, str]] = [
    # ── Technology ──
    ("AAPL", "Technology", "NASDAQ"),
    ("MSFT", "Technology", "NASDAQ"),
    ("NVDA", "Technology", "NASDAQ"),
    ("AVGO", "Technology", "NASDAQ"),
    ("ORCL", "Technology", "NYSE"),
    ("CRM", "Technology", "NYSE"),
    ("AMD", "Technology", "NASDAQ"),
    ("ADBE", "Technology", "NASDAQ"),
    ("CSCO", "Technology", "NASDAQ"),
    ("ACN", "Technology", "NYSE"),
    ("IBM", "Technology", "NYSE"),
    ("INTU", "Technology", "NASDAQ"),
    ("TXN", "Technology", "NASDAQ"),
    ("QCOM", "Technology", "NASDAQ"),
    ("AMAT", "Technology", "NASDAQ"),
    ("NOW", "Technology", "NYSE"),
    ("PANW", "Technology", "NASDAQ"),
    ("MU", "Technology", "NASDAQ"),
    ("LRCX", "Technology", "NASDAQ"),
    ("ADI", "Technology", "NASDAQ"),
    ("KLAC", "Technology", "NASDAQ"),
    ("SNPS", "Technology", "NASDAQ"),
    ("CDNS", "Technology", "NASDAQ"),
    ("CRWD", "Technology", "NASDAQ"),
    ("MCHP", "Technology", "NASDAQ"),
    ("MSI", "Technology", "NYSE"),
    ("FTNT", "Technology", "NASDAQ"),
    ("ROP", "Technology", "NASDAQ"),
    ("NXPI", "Technology", "NASDAQ"),
    ("ON", "Technology", "NASDAQ"),
    ("MPWR", "Technology", "NASDAQ"),
    ("FSLR", "Technology", "NASDAQ"),
    ("IT", "Technology", "NYSE"),
    ("KEYS", "Technology", "NYSE"),
    ("ANSS", "Technology", "NASDAQ"),
    ("CDW", "Technology", "NASDAQ"),
    ("HPQ", "Technology", "NYSE"),
    ("HPE", "Technology", "NYSE"),
    ("ZBRA", "Technology", "NASDAQ"),
    ("TDY", "Technology", "NYSE"),
    ("SWKS", "Technology", "NASDAQ"),
    ("PTC", "Technology", "NASDAQ"),
    ("TRMB", "Technology", "NASDAQ"),
    ("TER", "Technology", "NASDAQ"),
    ("NTAP", "Technology", "NASDAQ"),
    ("GEN", "Technology", "NASDAQ"),
    ("JNPR", "Technology", "NYSE"),
    ("EPAM", "Technology", "NYSE"),
    ("QRVO", "Technology", "NASDAQ"),
    # ── Healthcare ──
    ("LLY", "Healthcare", "NYSE"),
    ("UNH", "Healthcare", "NYSE"),
    ("JNJ", "Healthcare", "NYSE"),
    ("ABBV", "Healthcare", "NYSE"),
    ("MRK", "Healthcare", "NYSE"),
    ("TMO", "Healthcare", "NYSE"),
    ("ABT", "Healthcare", "NYSE"),
    ("DHR", "Healthcare", "NYSE"),
    ("AMGN", "Healthcare", "NASDAQ"),
    ("PFE", "Healthcare", "NYSE"),
    ("ISRG", "Healthcare", "NASDAQ"),
    ("SYK", "Healthcare", "NYSE"),
    ("VRTX", "Healthcare", "NASDAQ"),
    ("BSX", "Healthcare", "NYSE"),
    ("GILD", "Healthcare", "NASDAQ"),
    ("MDT", "Healthcare", "NYSE"),
    ("ELV", "Healthcare", "NYSE"),
    ("CI", "Healthcare", "NYSE"),
    ("REGN", "Healthcare", "NASDAQ"),
    ("BDX", "Healthcare", "NYSE"),
    ("ZTS", "Healthcare", "NYSE"),
    ("HCA", "Healthcare", "NYSE"),
    ("MCK", "Healthcare", "NYSE"),
    ("A", "Healthcare", "NYSE"),
    ("EW", "Healthcare", "NYSE"),
    ("IDXX", "Healthcare", "NASDAQ"),
    ("DXCM", "Healthcare", "NASDAQ"),
    ("IQV", "Healthcare", "NYSE"),
    ("COR", "Healthcare", "NYSE"),
    ("RMD", "Healthcare", "NYSE"),
    ("MTD", "Healthcare", "NYSE"),
    ("WAT", "Healthcare", "NYSE"),
    ("BAX", "Healthcare", "NYSE"),
    ("HOLX", "Healthcare", "NASDAQ"),
    ("ALGN", "Healthcare", "NASDAQ"),
    ("PODD", "Healthcare", "NASDAQ"),
    ("MOH", "Healthcare", "NYSE"),
    ("CRL", "Healthcare", "NYSE"),
    ("RVTY", "Healthcare", "NYSE"),
    ("VTRS", "Healthcare", "NASDAQ"),
    ("INCY", "Healthcare", "NASDAQ"),
    ("HSIC", "Healthcare", "NASDAQ"),
    ("TECH", "Healthcare", "NASDAQ"),
    ("CTLT", "Healthcare", "NYSE"),
    ("BIO", "Healthcare", "NYSE"),
    ("LH", "Healthcare", "NYSE"),
    # ── Financials ──
    ("BRK B", "Financials", "NYSE"),
    ("JPM", "Financials", "NYSE"),
    ("V", "Financials", "NYSE"),
    ("MA", "Financials", "NYSE"),
    ("BAC", "Financials", "NYSE"),
    ("WFC", "Financials", "NYSE"),
    ("GS", "Financials", "NYSE"),
    ("MS", "Financials", "NYSE"),
    ("SPGI", "Financials", "NYSE"),
    ("BLK", "Financials", "NYSE"),
    ("AXP", "Financials", "NYSE"),
    ("C", "Financials", "NYSE"),
    ("SCHW", "Financials", "NYSE"),
    ("PGR", "Financials", "NYSE"),
    ("CB", "Financials", "NYSE"),
    ("MMC", "Financials", "NYSE"),
    ("ICE", "Financials", "NYSE"),
    ("CME", "Financials", "NASDAQ"),
    ("USB", "Financials", "NYSE"),
    ("AON", "Financials", "NYSE"),
    ("MCO", "Financials", "NYSE"),
    ("AJG", "Financials", "NYSE"),
    ("PNC", "Financials", "NYSE"),
    ("TFC", "Financials", "NYSE"),
    ("MET", "Financials", "NYSE"),
    ("AIG", "Financials", "NYSE"),
    ("TRV", "Financials", "NYSE"),
    ("MSCI", "Financials", "NYSE"),
    ("FIS", "Financials", "NYSE"),
    ("COF", "Financials", "NYSE"),
    ("AFL", "Financials", "NYSE"),
    ("BK", "Financials", "NYSE"),
    ("ALL", "Financials", "NYSE"),
    ("AMP", "Financials", "NYSE"),
    ("PRU", "Financials", "NYSE"),
    ("FI", "Financials", "NYSE"),
    ("DFS", "Financials", "NYSE"),
    ("FITB", "Financials", "NASDAQ"),
    ("NDAQ", "Financials", "NASDAQ"),
    ("STT", "Financials", "NYSE"),
    ("HBAN", "Financials", "NASDAQ"),
    ("MTB", "Financials", "NYSE"),
    ("RF", "Financials", "NYSE"),
    ("CFG", "Financials", "NYSE"),
    ("KEY", "Financials", "NYSE"),
    ("NTRS", "Financials", "NASDAQ"),
    ("CINF", "Financials", "NASDAQ"),
    ("CBOE", "Financials", "CBOE"),
    ("SYF", "Financials", "NYSE"),
    ("RJF", "Financials", "NYSE"),
    ("BRO", "Financials", "NYSE"),
    ("WRB", "Financials", "NYSE"),
    ("L", "Financials", "NYSE"),
    ("RE", "Financials", "NYSE"),
    ("GL", "Financials", "NYSE"),
    ("MKTX", "Financials", "NASDAQ"),
    ("IVZ", "Financials", "NYSE"),
    ("BEN", "Financials", "NYSE"),
    # ── Consumer Discretionary ──
    ("AMZN", "Consumer Discretionary", "NASDAQ"),
    ("TSLA", "Consumer Discretionary", "NASDAQ"),
    ("HD", "Consumer Discretionary", "NYSE"),
    ("MCD", "Consumer Discretionary", "NYSE"),
    ("LOW", "Consumer Discretionary", "NYSE"),
    ("NKE", "Consumer Discretionary", "NYSE"),
    ("BKNG", "Consumer Discretionary", "NASDAQ"),
    ("SBUX", "Consumer Discretionary", "NASDAQ"),
    ("TJX", "Consumer Discretionary", "NYSE"),
    ("CMG", "Consumer Discretionary", "NYSE"),
    ("ORLY", "Consumer Discretionary", "NASDAQ"),
    ("AZO", "Consumer Discretionary", "NYSE"),
    ("MAR", "Consumer Discretionary", "NASDAQ"),
    ("HLT", "Consumer Discretionary", "NYSE"),
    ("ROST", "Consumer Discretionary", "NASDAQ"),
    ("DHI", "Consumer Discretionary", "NYSE"),
    ("GM", "Consumer Discretionary", "NYSE"),
    ("LEN", "Consumer Discretionary", "NYSE"),
    ("F", "Consumer Discretionary", "NYSE"),
    ("DKNG", "Consumer Discretionary", "NASDAQ"),
    ("PHM", "Consumer Discretionary", "NYSE"),
    ("YUM", "Consumer Discretionary", "NYSE"),
    ("GPC", "Consumer Discretionary", "NYSE"),
    ("ULTA", "Consumer Discretionary", "NASDAQ"),
    ("EBAY", "Consumer Discretionary", "NASDAQ"),
    ("NVR", "Consumer Discretionary", "NYSE"),
    ("RCL", "Consumer Discretionary", "NYSE"),
    ("CCL", "Consumer Discretionary", "NYSE"),
    ("DPZ", "Consumer Discretionary", "NYSE"),
    ("POOL", "Consumer Discretionary", "NASDAQ"),
    ("DRI", "Consumer Discretionary", "NYSE"),
    ("BBY", "Consumer Discretionary", "NYSE"),
    ("LVS", "Consumer Discretionary", "NYSE"),
    ("WYNN", "Consumer Discretionary", "NASDAQ"),
    ("MGM", "Consumer Discretionary", "NYSE"),
    ("KMX", "Consumer Discretionary", "NYSE"),
    ("APTV", "Consumer Discretionary", "NYSE"),
    ("GRMN", "Consumer Discretionary", "NYSE"),
    ("TSCO", "Consumer Discretionary", "NASDAQ"),
    ("LKQ", "Consumer Discretionary", "NASDAQ"),
    ("BWA", "Consumer Discretionary", "NYSE"),
    ("CZR", "Consumer Discretionary", "NASDAQ"),
    ("ETSY", "Consumer Discretionary", "NASDAQ"),
    ("TPR", "Consumer Discretionary", "NYSE"),
    ("RL", "Consumer Discretionary", "NYSE"),
    ("HAS", "Consumer Discretionary", "NASDAQ"),
    ("MHK", "Consumer Discretionary", "NYSE"),
    ("NCLH", "Consumer Discretionary", "NYSE"),
    ("WHR", "Consumer Discretionary", "NYSE"),
    # ── Communication Services ──
    ("META", "Communication Services", "NASDAQ"),
    ("GOOGL", "Communication Services", "NASDAQ"),
    ("GOOG", "Communication Services", "NASDAQ"),
    ("NFLX", "Communication Services", "NASDAQ"),
    ("DIS", "Communication Services", "NYSE"),
    ("CMCSA", "Communication Services", "NASDAQ"),
    ("T", "Communication Services", "NYSE"),
    ("VZ", "Communication Services", "NYSE"),
    ("TMUS", "Communication Services", "NASDAQ"),
    ("CHTR", "Communication Services", "NASDAQ"),
    ("EA", "Communication Services", "NASDAQ"),
    ("WBD", "Communication Services", "NASDAQ"),
    ("TTWO", "Communication Services", "NASDAQ"),
    ("MTCH", "Communication Services", "NASDAQ"),
    ("OMC", "Communication Services", "NYSE"),
    ("IPG", "Communication Services", "NYSE"),
    ("LYV", "Communication Services", "NYSE"),
    ("PARA", "Communication Services", "NASDAQ"),
    ("FOXA", "Communication Services", "NASDAQ"),
    ("FOX", "Communication Services", "NASDAQ"),
    ("NWSA", "Communication Services", "NASDAQ"),
    ("NWS", "Communication Services", "NASDAQ"),
    # ── Industrials ──
    ("GE", "Industrials", "NYSE"),
    ("CAT", "Industrials", "NYSE"),
    ("UNP", "Industrials", "NYSE"),
    ("HON", "Industrials", "NASDAQ"),
    ("RTX", "Industrials", "NYSE"),
    ("UPS", "Industrials", "NYSE"),
    ("BA", "Industrials", "NYSE"),
    ("DE", "Industrials", "NYSE"),
    ("LMT", "Industrials", "NYSE"),
    ("ADP", "Industrials", "NASDAQ"),
    ("GD", "Industrials", "NYSE"),
    ("ETN", "Industrials", "NYSE"),
    ("NOC", "Industrials", "NYSE"),
    ("ITW", "Industrials", "NYSE"),
    ("MMM", "Industrials", "NYSE"),
    ("WM", "Industrials", "NYSE"),
    ("EMR", "Industrials", "NYSE"),
    ("CSX", "Industrials", "NASDAQ"),
    ("FDX", "Industrials", "NYSE"),
    ("NSC", "Industrials", "NYSE"),
    ("PCAR", "Industrials", "NASDAQ"),
    ("JCI", "Industrials", "NYSE"),
    ("CTAS", "Industrials", "NASDAQ"),
    ("PH", "Industrials", "NYSE"),
    ("CMI", "Industrials", "NYSE"),
    ("TT", "Industrials", "NYSE"),
    ("CARR", "Industrials", "NYSE"),
    ("OTIS", "Industrials", "NYSE"),
    ("ROK", "Industrials", "NYSE"),
    ("FAST", "Industrials", "NASDAQ"),
    ("GWW", "Industrials", "NYSE"),
    ("AME", "Industrials", "NYSE"),
    ("VRSK", "Industrials", "NASDAQ"),
    ("IR", "Industrials", "NYSE"),
    ("CPRT", "Industrials", "NASDAQ"),
    ("PWR", "Industrials", "NYSE"),
    ("DOV", "Industrials", "NYSE"),
    ("XYL", "Industrials", "NYSE"),
    ("HWM", "Industrials", "NYSE"),
    ("PAYX", "Industrials", "NASDAQ"),
    ("HUBB", "Industrials", "NYSE"),
    ("SNA", "Industrials", "NYSE"),
    ("LDOS", "Industrials", "NYSE"),
    ("J", "Industrials", "NYSE"),
    ("EFX", "Industrials", "NYSE"),
    ("WAB", "Industrials", "NYSE"),
    ("RSG", "Industrials", "NYSE"),
    ("GPN", "Industrials", "NYSE"),
    ("DAL", "Industrials", "NYSE"),
    ("UAL", "Industrials", "NASDAQ"),
    ("LUV", "Industrials", "NYSE"),
    ("MAS", "Industrials", "NYSE"),
    ("ROL", "Industrials", "NYSE"),
    ("IEX", "Industrials", "NYSE"),
    ("NDSN", "Industrials", "NASDAQ"),
    ("TXT", "Industrials", "NYSE"),
    ("SWK", "Industrials", "NYSE"),
    # ── Consumer Staples ──
    ("PG", "Consumer Staples", "NYSE"),
    ("KO", "Consumer Staples", "NYSE"),
    ("PEP", "Consumer Staples", "NASDAQ"),
    ("COST", "Consumer Staples", "NASDAQ"),
    ("WMT", "Consumer Staples", "NYSE"),
    ("PM", "Consumer Staples", "NYSE"),
    ("MO", "Consumer Staples", "NYSE"),
    ("MDLZ", "Consumer Staples", "NASDAQ"),
    ("CL", "Consumer Staples", "NYSE"),
    ("EL", "Consumer Staples", "NYSE"),
    ("KMB", "Consumer Staples", "NYSE"),
    ("ADM", "Consumer Staples", "NYSE"),
    ("STZ", "Consumer Staples", "NYSE"),
    ("SYY", "Consumer Staples", "NYSE"),
    ("GIS", "Consumer Staples", "NYSE"),
    ("KDP", "Consumer Staples", "NASDAQ"),
    ("HSY", "Consumer Staples", "NYSE"),
    ("K", "Consumer Staples", "NYSE"),
    ("KR", "Consumer Staples", "NYSE"),
    ("MNST", "Consumer Staples", "NASDAQ"),
    ("MKC", "Consumer Staples", "NYSE"),
    ("CHD", "Consumer Staples", "NYSE"),
    ("CAG", "Consumer Staples", "NYSE"),
    ("SJM", "Consumer Staples", "NYSE"),
    ("TSN", "Consumer Staples", "NYSE"),
    ("HRL", "Consumer Staples", "NYSE"),
    ("CPB", "Consumer Staples", "NYSE"),
    ("CLX", "Consumer Staples", "NYSE"),
    ("TAP", "Consumer Staples", "NYSE"),
    ("BG", "Consumer Staples", "NYSE"),
    # ── Energy ──
    ("XOM", "Energy", "NYSE"),
    ("CVX", "Energy", "NYSE"),
    ("COP", "Energy", "NYSE"),
    ("SLB", "Energy", "NYSE"),
    ("EOG", "Energy", "NYSE"),
    ("MPC", "Energy", "NYSE"),
    ("PXD", "Energy", "NYSE"),
    ("PSX", "Energy", "NYSE"),
    ("VLO", "Energy", "NYSE"),
    ("OXY", "Energy", "NYSE"),
    ("WMB", "Energy", "NYSE"),
    ("HES", "Energy", "NYSE"),
    ("HAL", "Energy", "NYSE"),
    ("DVN", "Energy", "NYSE"),
    ("KMI", "Energy", "NYSE"),
    ("BKR", "Energy", "NASDAQ"),
    ("FANG", "Energy", "NASDAQ"),
    ("OKE", "Energy", "NYSE"),
    ("CTRA", "Energy", "NYSE"),
    ("TRGP", "Energy", "NYSE"),
    ("MRO", "Energy", "NYSE"),
    ("EQT", "Energy", "NYSE"),
    ("APA", "Energy", "NASDAQ"),
    # ── Materials ──
    ("LIN", "Materials", "NYSE"),
    ("APD", "Materials", "NYSE"),
    ("SHW", "Materials", "NYSE"),
    ("FCX", "Materials", "NYSE"),
    ("ECL", "Materials", "NYSE"),
    ("NEM", "Materials", "NYSE"),
    ("NUE", "Materials", "NYSE"),
    ("DOW", "Materials", "NYSE"),
    ("DD", "Materials", "NYSE"),
    ("CTVA", "Materials", "NYSE"),
    ("PPG", "Materials", "NYSE"),
    ("VMC", "Materials", "NYSE"),
    ("MLM", "Materials", "NYSE"),
    ("IFF", "Materials", "NYSE"),
    ("CF", "Materials", "NYSE"),
    ("ALB", "Materials", "NYSE"),
    ("PKG", "Materials", "NYSE"),
    ("STLD", "Materials", "NASDAQ"),
    ("IP", "Materials", "NYSE"),
    ("AVY", "Materials", "NYSE"),
    ("EMN", "Materials", "NYSE"),
    ("CE", "Materials", "NYSE"),
    ("BALL", "Materials", "NYSE"),
    ("FMC", "Materials", "NYSE"),
    ("AMCR", "Materials", "NYSE"),
    # ── Utilities ──
    ("NEE", "Utilities", "NYSE"),
    ("SO", "Utilities", "NYSE"),
    ("DUK", "Utilities", "NYSE"),
    ("D", "Utilities", "NYSE"),
    ("AEP", "Utilities", "NASDAQ"),
    ("SRE", "Utilities", "NYSE"),
    ("EXC", "Utilities", "NASDAQ"),
    ("XEL", "Utilities", "NASDAQ"),
    ("ED", "Utilities", "NYSE"),
    ("WEC", "Utilities", "NYSE"),
    ("PCG", "Utilities", "NYSE"),
    ("ES", "Utilities", "NYSE"),
    ("AWK", "Utilities", "NYSE"),
    ("EIX", "Utilities", "NYSE"),
    ("DTE", "Utilities", "NYSE"),
    ("AEE", "Utilities", "NYSE"),
    ("FE", "Utilities", "NYSE"),
    ("PPL", "Utilities", "NYSE"),
    ("ETR", "Utilities", "NYSE"),
    ("CMS", "Utilities", "NYSE"),
    ("CEG", "Utilities", "NASDAQ"),
    ("CNP", "Utilities", "NYSE"),
    ("ATO", "Utilities", "NYSE"),
    ("EVRG", "Utilities", "NYSE"),
    ("NI", "Utilities", "NYSE"),
    ("LNT", "Utilities", "NASDAQ"),
    ("PNW", "Utilities", "NYSE"),
    # ── Real Estate ──
    ("PLD", "Real Estate", "NYSE"),
    ("AMT", "Real Estate", "NYSE"),
    ("CCI", "Real Estate", "NYSE"),
    ("EQIX", "Real Estate", "NASDAQ"),
    ("PSA", "Real Estate", "NYSE"),
    ("WELL", "Real Estate", "NYSE"),
    ("DLR", "Real Estate", "NYSE"),
    ("O", "Real Estate", "NYSE"),
    ("SPG", "Real Estate", "NYSE"),
    ("VICI", "Real Estate", "NYSE"),
    ("AVB", "Real Estate", "NYSE"),
    ("EQR", "Real Estate", "NYSE"),
    ("IRM", "Real Estate", "NYSE"),
    ("SBAC", "Real Estate", "NASDAQ"),
    ("WY", "Real Estate", "NYSE"),
    ("ARE", "Real Estate", "NYSE"),
    ("MAA", "Real Estate", "NYSE"),
    ("EXR", "Real Estate", "NYSE"),
    ("VTR", "Real Estate", "NYSE"),
    ("CBRE", "Real Estate", "NYSE"),
    ("ESS", "Real Estate", "NYSE"),
    ("UDR", "Real Estate", "NYSE"),
    ("HST", "Real Estate", "NASDAQ"),
    ("REG", "Real Estate", "NYSE"),
    ("KIM", "Real Estate", "NYSE"),
    ("CPT", "Real Estate", "NYSE"),
    ("BXP", "Real Estate", "NYSE"),
    ("PEAK", "Real Estate", "NYSE"),
    ("FRT", "Real Estate", "NYSE"),
]

KNOWN_ETFS: frozenset[str] = frozenset({
    "SPY", "QQQ", "IWM", "DIA", "VOO", "VTI", "IVV",
    "XLK", "XLV", "XLF", "XLE", "XLY", "XLP", "XLI",
    "XLB", "XLU", "XLRE", "XLC", "GLD", "SLV", "HYG",
    "TLT", "IEF", "LQD", "EFA", "EEM", "VEA", "VWO",
    "ARKK", "SOXL", "TQQQ", "SQQQ", "XBI", "SMH",
})
